<?php

namespace App\Models;

use App\Models\Scopes\ArticleGlobalScope;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Mapi\Easyapi\Models\ApiModel;

/***
 *
 */
class Article extends ApiModel
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::addGlobalScope(new ArticleGlobalScope());
    }

    protected $fillable = [
        'title',
        'content',
        'status',
        'user_id',
        'reviewed_by',
        'approved_by'
    ];

    protected $allowedFilters = [
        '*'
    ];

    protected $allowedRelationsToLoad = [
        'user' => ['id', 'name'],
        'reviewer' => ['id', 'name'],
        'approvedBy' => ['id', 'name'],
        'comments' => ['id', 'article_id', 'text']
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function reviewer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    public function approvedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }
}
